### ISSUE TITLE
-U and -D for one macro cannot be both present on the commandline 

### ISSUE THREAD

**Issue by matthijskooijman** [BR903/cppp#1]
```
$ cppp -Ufoo -Dfoo foo.c
cppp: symbol foo cannot be both defined and undefined
```

Is there any particular reason to forbid this? I have a usecase where
defines can end up both undefined and defined on the same commandline.
The order defines which should take precedence, just like the regular
cpp, which does not complain:

```
$ cpp -Ufoo -Dfoo foo.c
#1 "foo.c"
#1 "<built-in>"
#1 "<command-line>"
#1 "/usr/include/stdc-predef.h" 1 3 4
#1 "<command-line>" 2
#1 "foo.c"
```

**Comment by matthijskooijman** [comment]
Here's a patch, btw. It was quicker to patch cppp than change my commandline generation just now, so I did the former. If you want a PR, let me know:


	diff --git a/cppp.c b/cppp.c
	index e3ab285..f79acd6 100644
	--- a/cppp.c
	+++ b/cppp.c
	@@ -100,8 +100,7 @@ static int readcmdline(int argc, char *argv[],
		    } else {
			value = 1;
		    }
	-           if (findsymbolinset(undefs, arg, NULL))
	-               fail("symbol %s cannot be both defined and undefined", arg);
	+           removesymbolfromset(undefs, arg);
		    addsymboltoset(defs, arg, value);
		} else if (argv[i][1] == 'U') {
		    arg = argv[i] + 2;
	@@ -111,8 +110,7 @@ static int readcmdline(int argc, char *argv[],
			else
			    fail("missing argument to -U");
		    }
	-           if (findsymbolinset(defs, arg, NULL))
	-               fail("symbol %s cannot be both defined and undefined", arg);
	+           removesymbolfromset(defs, arg);
		    addsymboltoset(undefs, arg, 0L);
		} else {
		    fail("invalid option: %s", argv[i]);
	diff --git a/symset.c b/symset.c
	index efaead5..a06de78 100644
	--- a/symset.c
	+++ b/symset.c
	@@ -105,3 +105,23 @@ int findsymbolinset(struct symset const *set, char const *id, long *value)
	     }
	     return FALSE;
	 }
	+
	+/* Remove a symbol from the set (if present). Returns TRUE if something
	+ * was removed, FALSE otherwise.
	+ */
	+int removesymbolfromset(struct symset *set, char const *id)
	+{
	+    int i;
	+
	+    for (i = 0 ; i < set->size ; ++i) {
	+       if (!idcmp(set->syms[i].id, id)) {
	+           // Move the last element to fill the spot (if there is only
	+           // 1 element, this is just a no-op)
	+           set->syms[i] = set->syms[set->size - 1];
	+           --set->size;
	+
	+           return TRUE;
	+       }
	+    }
	+    return FALSE;
	+}
	diff --git a/symset.h b/symset.h
	index ac704c2..20d5e72 100644
	--- a/symset.h
	+++ b/symset.h
	@@ -34,4 +34,9 @@ extern void addsymboltoset(struct symset *set, char const *id, long value);
	 extern int findsymbolinset(struct symset const *set,
				   char const *id, long *value);
	 
	+/* Remove a symbol from the set (if present). Returns TRUE if something
	+ * was removed, FALSE otherwise.
	+ */
	+extern int removesymbolfromset(struct symset *set, char const *id);
	+
	 #endif

**Comment by BR903** [comment]
>     $ cppp -Ufoo -Dfoo foo.c
>     cppp: symbol foo cannot be both defined and undefined
> 
> Is there any particular reason to forbid this?

Just that it's more likely to be accidental than intentional. It's
good to let users know when they make nonsensical requests.

> The order defines which should take precedence, just like the regular
> cpp, which does not complain:

That's a good point; cppp's behavior should be close to cpp's.
